---
- name: Download Gitlab MkII
  hosts: gitlab
  remote_user: azuser
  become: true
  tasks:
          #- name: configure external url
     #   lineinfile:
             #path: /etc/gitlab/gitlab.rb
        #regexp: 'external_url 'http://gitlab.example.com''
        #        line: external_url http://gitlab-test.australiaeast.cloudapp.azure.com
    - name: configure external url
      lineinfile:
         path: /etc/gitlab/gitlab.rb
         regexp: '^test'
         line: "external_url 'http://gitlab-test.australiaeast.cloudapp.azure.com'"

