---
  - name: testbook
    hosts: network
    connection: local
    remote_user: admin
    #become: yes
    #become_method: enable
    gather_facts: false
    tasks:
            - name: save config
              ios_config:
                      save_when: always
              register: output

            - name: DEBUG >> output
              debug:
                      msg: "{{ output }}"

