---
  - name: Create Azure VM
    hosts: localhost
    connection: local

    vars:
     resource_group: "samsojl1_sp"

    vars_files:
      - csv4.yaml

    tasks:
            #- name: Create virtual network
      #azure_rm_virtualnetwork:
              #resource_group: "{{ resource_group }}"
        #name: "{{ Net }}"
        #        address_prefixes: "10.0.0.0/16"

    - name: Create Network Security Group that allows SSH
      azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: "{{ NSG }}"
