---
  - hosts: localhost
    vars:
     vm_nsg: "{{test.list.0.NSG}}"
    tasks:      
      - read_csv:
                path: dtest.csv
        register: test

      - set_fact:
          vm_nsg: "{{test.list.0.NSG | (item)}}"
        with_sequence: start=0 end=4

      - name: Create Network Security Group that allows SSH

        azure_rm_securitygroup:
          resource_group: "samsojl1_sp"
          name: "{{ vm_nsg }}"
        
        loop: "{{ test.list }}"

