---
  - hosts: localhost
    vars :
     inc: '0'
     var1: 'test'
     NSG: '{{var1}}'

    tasks:
      - read_csv:
                path: dtest.csv
        register: users
        delegate_to: localhost

      - debug:
          msg: "{{users.list.item.NSG}}"
      - set_fact:
          var1: "{{users.list.item.NSG}}"

        loop: '{{users.list}}'

      - name: Create Network Security Group that allows SSH
        azure_rm_securitygroup:
          resource_group: "samsojl1_sp"
          name: "{{ users.list.item.NSG }}"

        loop: '{{users.list}}'
