---
  - hosts: localhost

    tasks:
      - read_csv:
                path: dtest.csv
        register: users
        delegate_to: localhost

      - name: Create Network Security Group that allows SSH
        azure_rm_securitygroup:
            resource_group: "samsojl1_sp"
            name: "{{ item.NSG }}"

        loop: '{{users.list}}'
